### ISSUE TITLE
Auto suggation box doesn't open if we use BR tag on enter key instead of P tag.

### ISSUE THREAD

**Issue by masihur** [CogniStreamer/tinyMCE-mention#23]
Hi,
I have used tinyMCE 3.5 version. We use BR tag for enter key instead of P tag (default feature of tinyMCE). In this case if a user press enter key then auto-suggestion box doesn't open on @symbol.
Applied a condition into the function o(). After that issue have been fixed.
Code as below.

```
function o() {
    var n = t((e.selection.getNode().outerHTML).replace("<br>","&nbsp;")),
    r = n.text(),
    i = r.substr(r.length - 1, 1);   
    return !!t.trim(i).length ? false : true
}
```
Please review it and add this into your original library.

**Comment by StevenDevooght** [comment]
Hi,

I understand the problem. The problem is that `e.selection.getNode()` does not work properly when using tinyMCE 3.5 with `force_br_newlines`. It's also strongly advised to [not use](http://www.tinymce.com/wiki.php/Configuration3x:force_br_newlines) the option.

For now I suggest that you disable the `force_br_newlines` if possible.

**Comment by StevenDevooght** [comment]
I fixed the `prevCharIsSpace` function so it also works with `force_br_newlines` enabled.

**Comment by masihur** [comment]
Hi,
Thank You Steven Devooght.
